# Generated by Django 2.1.7 on 2019-07-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board_FileManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_Files', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CDC_Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_Title', models.CharField(max_length=150, null=True)),
                ('Board_Content', models.CharField(max_length=1000)),
                ('Board_CreateDate', models.DateTimeField(null=True)),
                ('Board_ClassCode', models.CharField(blank=True, choices=[('1', 'C'), ('2', 'C++'), ('3', 'C#'), ('4', 'PYTHON'), ('5', 'JAVA'), ('6', 'WEB'), ('7', 'DB'), ('8', '기타')], default='기타', max_length=10, null=True)),
                ('Board_Files', models.FileField(blank=True, null=True, upload_to='')),
                ('Board_hits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CDC_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('recommend', models.IntegerField(default=0)),
                ('comment_Board', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='acincodingclinic.CDC_Board')),
            ],
        ),
        migrations.CreateModel(
            name='CDC_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error_Title', models.CharField(max_length=150)),
                ('Error_Content', models.CharField(max_length=1000)),
                ('Error_Files', models.FileField(blank=True, null=True, upload_to='')),
                ('Error_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coaching_Title', models.CharField(max_length=150, null=True)),
                ('Coaching_CreateDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Coaching_Code', models.IntegerField(null=True)),
                ('Coaching_ClassCode', models.CharField(blank=True, choices=[('1', 'C'), ('2', 'C++'), ('3', 'C#'), ('4', 'PYTHON'), ('5', 'JAVA'), ('6', 'WEB'), ('7', 'DB'), ('8', '기타')], default='기타', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coaching_FileManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coaching_Files', models.FileField(blank=True, null=True, upload_to='')),
                ('Coaching_FileConnect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acincodingclinic.Coaching')),
            ],
        ),
        migrations.CreateModel(
            name='Error_FileManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error_Files', models.FileField(blank=True, null=True, upload_to='')),
                ('Error_FileConnect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acincodingclinic.CDC_Error')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDC_ID', models.CharField(max_length=20, null=True)),
                ('CDC_PW', models.CharField(max_length=20, null=True)),
                ('CDC_Name', models.CharField(max_length=15, null=True)),
                ('CDC_Birth', models.CharField(max_length=10, null=True)),
                ('CDC_PhoneNumber', models.CharField(max_length=11, null=True)),
                ('CDC_Email', models.CharField(max_length=100, null=True)),
                ('CDC_Gender', models.CharField(max_length=1, null=True)),
                ('CDC_job', models.CharField(choices=[('1', '초등학생'), ('2', '중학생'), ('3', '고등학생'), ('4', '대학생'), ('5', '직장인')], default='4', max_length=10, null=True)),
                ('CDC_isAdmin', models.BooleanField(default=False)),
                ('CDC_Personal_Information_Agreement', models.CharField(default='1', max_length=1, null=True, verbose_name='개인정보동의')),
                ('rank', models.CharField(choices=[('1', '시스템관리자'), ('2', '사용자')], default='2', max_length=10, null=True)),
                ('CDC_SignUpDate', models.DateTimeField(null=True)),
                ('CDC_LastDate', models.DateTimeField(null=True)),
                ('CDC_ClientAddress', models.CharField(max_length=32, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='Point_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acincodingclinic.User'),
        ),
        migrations.AddField(
            model_name='coaching',
            name='Coaching_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acincodingclinic.User'),
        ),
        migrations.AddField(
            model_name='cdc_error',
            name='Error_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acincodingclinic.User'),
        ),
        migrations.AddField(
            model_name='cdc_board',
            name='Board_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acincodingclinic.User'),
        ),
        migrations.AddField(
            model_name='board_filemanagement',
            name='Board_FileConnect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acincodingclinic.CDC_Board'),
        ),
    ]
